nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependenciesMeta:
      typescript:
        optional: true
  "eslint-config-react-app@6.0.0":
    peerDependenciesMeta:
      babel-eslint:
        optional: true

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
