nodeLinker: node-modules

packageExtensions:
  "@aws-sdk/client-s3@3.54.1":
    peerDependenciesMeta:
      "@aws-sdk/signature-v4-crt":
        optional: true
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@parcel/transformer-js@*":
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
  "@parcel/types@*":
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
  eslint-config-react-app@6.0.0:
    peerDependenciesMeta:
      babel-eslint:
        optional: true
  fork-ts-checker-webpack-plugin@4.1.6:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
