name: Build s3-static-site-uploader

on:
  push:
    branches-ignore:
      - main
      - develop
    paths:
      - .github/workflows/build-s3-static-site-uploader.yaml
      - packages/s3-static-site-uploader/**
      - yarn.lock

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      workDir: ./packages/s3-static-site-uploader
