name: Build prettier-config

on:
  push:
    branches-ignore:
      - main
      - develop
    paths:
      - .github/workflows/build-prettier-config.yaml
      - packages/prettier-config/**
      - yarn.lock

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      workDir: ./packages/prettier-config
