name: Build website

on:
  push:
    branches-ignore:
      - main
      - develop
    paths:
      - .github/workflows/build-website.yaml
      - packages/website/**
      - yarn.lock

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      workDir: ./packages/website
