name: Build

on:
  workflow_call:
    inputs:
      workDir:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workDir }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn workspaces focus
      - run: yarn build
      - run: yarn check
      - run: yarn test
