/* eslint-disable import/no-unused-modules */
import { Linter } from "eslint";

const config: Linter.Config = {
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:sonarjs/recommended",
    "plugin:import/recommended",
    "plugin:import/typescript",
  ],
  plugins: ["@typescript-eslint", "sonarjs"],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 12,
    sourceType: "module",
  },
  env: {
    es2021: true,
    browser: false,
    node: true,
  },
  rules: {
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-unused-vars": ["error"],
    "no-unused-vars": "off",
    "accessor-pairs": "error",
    "array-callback-return": ["error", { allowImplicit: true }],
    "arrow-body-style": "error",
    "class-methods-use-this": "error",
    complexity: ["error", 7],
    curly: ["error", "multi"],
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-notation": ["error", { allowKeywords: true }],
    eqeqeq: ["error", "smart"],
    "grouped-accessor-pairs": "error",
    "guard-for-in": "error",
    "import/first": "error",
    "import/newline-after-import": "error",
    "import/no-absolute-path": "error",
    "import/no-anonymous-default-export": "error",
    "import/no-cycle": "error",
    "import/no-default-export": "error",
    "import/no-duplicates": "error",
    "import/no-extraneous-dependencies": "error",
    "import/no-internal-modules": ["error", { allow: ["@apollo/client/core"] }],
    "import/no-unassigned-import": "error",
    "import/no-unused-modules": [
      "error",
      {
        missingExports: true,
        ignoreExports: ["index.ts"],
        unusedExports: false,
      },
    ],
    "import/no-useless-path-segments": "error",
    "import/no-self-import": "error",
    "import/unambiguous": "error",
    "max-classes-per-file": ["error", 1],
    "no-await-in-loop": "error",
    "no-caller": "error",
    "no-console": ["warn", { allow: ["warn", "error"] }],
    "no-constructor-return": "error",
    "no-div-regex": "error",
    "no-else-return": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-extra-parens": "off",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-implicit-coercion": ["error", { allow: ["!!"] }],
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-loop-func": "error",
    "no-loss-of-precision": "error",
    "no-promise-executor-return": "error",
    "no-template-curly-in-string": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-expressions": "error",
    "no-useless-backreference": "error",
    "prefer-arrow-callback": "error",
    quotes: ["error", "double", { avoidEscape: true }],
    "require-atomic-updates": "error",
  },
  ignorePatterns: ["**/dist/**/*"],
};

export = config;
